// Glossary terms — inspired by the paper's 900+ glossary, acronym, and math definitions.
// Curated to the most important terms for understanding the strategies in this terminal.

export interface GlossaryTerm {
  term: string;
  category: GlossaryCategory;
  definition: string;
  relatedStrategy?: string; // strategy id
  seeAlso?: string[];
}

export type GlossaryCategory =
  | "options"
  | "volatility"
  | "fixed-income"
  | "stocks"
  | "risk"
  | "macro"
  | "trading";

export const GLOSSARY_CATEGORIES: { id: GlossaryCategory; label: string; icon: string; color: string }[] = [
  { id: "options", label: "Options & Greeks", icon: "Layers", color: "text-emerald-400" },
  { id: "volatility", label: "Volatility", icon: "Activity", color: "text-rose-400" },
  { id: "fixed-income", label: "Fixed Income", icon: "Landmark", color: "text-sky-400" },
  { id: "stocks", label: "Stocks & Factors", icon: "TrendingUp", color: "text-emerald-400" },
  { id: "risk", label: "Risk & Portfolio", icon: "ShieldAlert", color: "text-amber-400" },
  { id: "macro", label: "Macro & FX", icon: "Globe", color: "text-cyan-400" },
  { id: "trading", label: "Trading & Execution", icon: "ArrowLeftRight", color: "text-violet-400" },
];

export const GLOSSARY: GlossaryTerm[] = [
  // ---------- OPTIONS & GREEKS ----------
  { term: "Call Option", category: "options", definition: "A contract giving the holder the right (but not the obligation) to buy an underlying asset at a specified strike price on or before expiration. Profit from rising prices.", relatedStrategy: "long-call" },
  { term: "Put Option", category: "options", definition: "A contract giving the holder the right to sell an underlying asset at a specified strike price on or before expiration. Profit from falling prices.", relatedStrategy: "long-put" },
  { term: "Strike Price (K)", category: "options", definition: "The fixed price at which an option holder can exercise their right to buy (call) or sell (put) the underlying asset." },
  { term: "Premium", category: "options", definition: "The price paid by the option buyer to the seller (writer) for the option contract. Determined by intrinsic value + time value." },
  { term: "Intrinsic Value", category: "options", definition: "The immediate exercise value of an option: max(S−K, 0) for a call, max(K−S, 0) for a put, where S is the spot price." },
  { term: "Time Value", category: "options", definition: "The portion of an option's premium above its intrinsic value, reflecting the probability of future favorable moves before expiration." },
  { term: "Moneyness (ITM/ATM/OTM)", category: "options", definition: "ITM = intrinsic value > 0 (profitable to exercise); ATM = strike ≈ spot; OTM = intrinsic value = 0 (not profitable to exercise)." },
  { term: "Delta (Δ)", category: "options", definition: "Rate of change of option price with respect to the underlying price. Call delta ∈ [0,1], put delta ∈ [-1,0]. Also approximates the hedge ratio and probability of finishing ITM.", relatedStrategy: "covered-call" },
  { term: "Gamma (Γ)", category: "options", definition: "Rate of change of delta with respect to the underlying price. Measures convexity — how quickly delta changes. Highest for ATM short-dated options." },
  { term: "Vega (ν)", category: "options", definition: "Rate of change of option price with respect to implied volatility (per 1% change). Long options are long vega; higher vol = higher option prices." },
  { term: "Theta (Θ)", category: "options", definition: "Rate of change of option price with respect to time (per day). Usually negative for long options (time decay) and positive for short options (income from decay)." },
  { term: "Rho (ρ)", category: "options", definition: "Rate of change of option price with respect to the risk-free interest rate. Usually small and neglected except for long-dated options." },
  { term: "Implied Volatility (IV)", category: "volatility", definition: "The volatility input that makes the Black-Scholes price equal to the observed market price. A forward-looking measure of expected volatility." },
  { term: "Realized Volatility (RV)", category: "volatility", definition: "The actual volatility of the underlying over a historical period, computed from observed returns. Typically annualized standard deviation of log returns." },
  { term: "Volatility Skew", category: "volatility", definition: "The pattern where OTM puts trade at higher implied vol than OTM calls (in equities). Reflects demand for downside protection. Traded via risk reversals.", relatedStrategy: "volatility-skew" },
  { term: "Volatility Smile", category: "volatility", definition: "The U-shaped pattern of implied volatility across strikes — ATM lowest, wings higher. Common in FX. Contrasts with the equity skew." },
  { term: "Volatility Risk Premium (VRP)", category: "volatility", definition: "The persistent gap where implied vol exceeds realized vol. Selling options harvests this premium but carries tail risk.", relatedStrategy: "volatility-risk-premium", seeAlso: ["Implied Volatility (IV)", "Realized Volatility (RV)"] },
  { term: "VIX", category: "volatility", definition: "The CBOE Volatility Index — a measure of the stock market's expectation of 30-day forward volatility derived from S&P 500 option prices. The 'fear gauge'." },
  { term: "Variance Swap", category: "volatility", definition: "A derivative that pays the difference between realized variance and a pre-agreed strike. Allows pure, delta-neutral volatility exposure.", relatedStrategy: "variance-swap" },
  { term: "Gamma Scalping", category: "volatility", definition: "The practice of delta-hedging a long-gamma position frequently to capture P&L from price oscillations, offsetting theta decay." },
  { term: "Pin Risk", category: "options", definition: "The risk near expiration that an ATM option's assignment is uncertain — the holder doesn't know whether they'll be assigned until after the close." },

  // ---------- OPTIONS STRATEGIES ----------
  { term: "Covered Call", category: "options", definition: "Long stock + short call. Generates income from theta while capping upside above the strike. The classic yield-enhancement overlay.", relatedStrategy: "covered-call" },
  { term: "Protective Put", category: "options", definition: "Long stock + long put. Acts as insurance — pays a premium to lock in a downside floor while retaining upside.", relatedStrategy: "protective-put" },
  { term: "Straddle", category: "options", definition: "Long (or short) call + put at the same strike and expiry. Long straddle profits from a large move either direction; short straddle from low vol.", relatedStrategy: "long-straddle" },
  { term: "Strangle", category: "options", definition: "Like a straddle but with OTM strikes. Cheaper to enter but requires a larger move to profit.", relatedStrategy: "long-strangle" },
  { term: "Butterfly Spread", category: "options", definition: "A 3-strike structure (1 long low, 2 short mid, 1 long high) that profits if the underlying pins at the middle strike at expiry.", relatedStrategy: "long-call-butterfly" },
  { term: "Iron Condor", category: "options", definition: "A defined-risk income structure combining a bull put spread + bear call spread. Profits if the underlying stays between the short strikes.", relatedStrategy: "long-iron-condor" },
  { term: "Risk Reversal", category: "options", definition: "Long OTM call + short OTM put (or vice versa). A low-cost directional trade that also expresses a view on the vol skew.", relatedStrategy: "risk-reversal" },
  { term: "Collar", category: "options", definition: "Long stock + long put (floor) + short call (cap). A zero-cost hedge when the put premium is financed by the call premium.", relatedStrategy: "collar" },
  { term: "Calendar Spread", category: "options", definition: "Long one expiry, short another at the same strike. Profits from time decay and term-structure moves." },
  { term: "Box Spread", category: "options", definition: "Bull call spread + bear put spread at the same strikes. Fixed payoff regardless of underlying — effectively a synthetic loan/deposit.", relatedStrategy: "long-box" },

  // ---------- FIXED INCOME ----------
  { term: "Duration", category: "fixed-income", definition: "A measure of a bond's price sensitivity to interest rate changes. Approximate % price change for a 1% yield change. Modified duration is the standard measure." },
  { term: "Convexity", category: "fixed-income", definition: "The second derivative of bond price with respect to yield. Measures how duration itself changes as yields move. Positive convexity (in callable bonds, negative) is beneficial." },
  { term: "DV01 (Dollar Duration)", category: "fixed-income", definition: "The dollar P&L change for a 1 basis point (0.01%) change in yield. Used for hedging and risk management across bond portfolios." },
  { term: "Yield Curve", category: "fixed-income", definition: "The plot of yields against maturity for bonds of the same credit quality. Normally upward-sloping (longer = higher yield); inversion signals recession risk." },
  { term: "Flattener / Steepener", category: "fixed-income", definition: "A curve trade betting that the yield spread between two maturities will narrow (flatten) or widen (steepen). Set up DV01-neutral.", relatedStrategy: "yield-curve-spread" },
  { term: "Carry", category: "fixed-income", definition: "The return earned by holding an asset — coupon income + roll-down the yield curve. A core factor across fixed income, FX, and commodities.", relatedStrategy: "carry-factor-fi" },
  { term: "Roll-Down", category: "fixed-income", definition: "The price appreciation from a bond 'rolling down' an upward-sloping yield curve as time passes and its maturity shortens." },
  { term: "OAS (Option-Adjusted Spread)", category: "fixed-income", definition: "The spread over the risk-free curve after removing the value of embedded options (e.g. callable bonds, MBS prepayment option). Measures pure credit risk." },
  { term: "CDS (Credit Default Swap)", category: "fixed-income", definition: "A derivative that pays out if a reference entity defaults. The buyer pays periodic premiums; the seller pays the loss given default.", relatedStrategy: "cds-basis-arb" },
  { term: "CDS-Bond Basis", category: "fixed-income", definition: "The difference between a bond's spread and the matching CDS spread. Positive basis (CDS > bond) is the norm; traded by arbitrageurs.", relatedStrategy: "cds-basis-arb" },
  { term: "REPO (Repurchase Agreement)", category: "fixed-income", definition: "A short-term secured loan: sell a security (collateral) and agree to buy it back at a higher price. The implied rate is the repo rate.", relatedStrategy: "repurchase-agreement" },

  // ---------- STOCKS & FACTORS ----------
  { term: "Momentum", category: "stocks", definition: "The empirical tendency for assets that have performed well recently to continue performing well (and vice versa). Cross-sectional momentum is among the most robust anomalies.", relatedStrategy: "price-momentum" },
  { term: "Value Factor", category: "stocks", definition: "The premium earned by holding cheap (high book-to-market, low P/E) stocks vs expensive stocks. Core Fama-French factor.", relatedStrategy: "value" },
  { term: "Mean Reversion", category: "stocks", definition: "The tendency for prices to revert to a historical average or equilibrium. Basis for pairs trading and statistical arbitrage.", relatedStrategy: "pairs-trading" },
  { term: "Cointegration", category: "stocks", definition: "A statistical relationship where two non-stationary series have a stationary linear combination. The basis for pairs trading — the spread mean-reverts.", relatedStrategy: "pairs-trading" },
  { term: "Statistical Arbitrage", category: "stocks", definition: "A market-neutral strategy exploiting short-term mean-reversion in cross-sectional stock returns. Typically dollar-neutral with many small positions.", relatedStrategy: "stat-arb-opt" },
  { term: "Dollar Neutrality", category: "stocks", definition: "Equal dollar amounts long and short, so net market exposure ≈ 0. A constraint in market-neutral strategies to isolate alpha from beta.", relatedStrategy: "stat-arb-opt" },
  { term: "Beta (β)", category: "stocks", definition: "The sensitivity of an asset's return to the market. β = 1 moves with the market; β > 1 more volatile; β < 1 less volatile; β < 0 inversely correlated." },
  { term: "Alpha (α)", category: "stocks", definition: "The excess return of an investment relative to its benchmark, after adjusting for beta. The 'skill' component of returns." },
  { term: "Betting Against Beta (BAB)", category: "stocks", definition: "The anomaly that low-beta stocks deliver higher risk-adjusted returns than CAPM predicts. Long low-β, short high-β.", relatedStrategy: "low-volatility-anomaly" },
  { term: "Post-Earnings Announcement Drift (PEAD)", category: "stocks", definition: "The tendency for stock prices to continue drifting in the direction of an earnings surprise for weeks after the announcement.", relatedStrategy: "earnings-momentum" },

  // ---------- RISK & PORTFOLIO ----------
  { term: "Sharpe Ratio", category: "risk", definition: "Risk-adjusted return: (mean excess return) / (standard deviation of returns). The flagship metric for strategy evaluation. >1 good, >2 excellent." },
  { term: "Sortino Ratio", category: "risk", definition: "Like Sharpe but penalizes only downside volatility (not upside). More appropriate for asymmetric return distributions." },
  { term: "Maximum Drawdown (MaxDD)", category: "risk", definition: "The largest peak-to-trough decline in the equity curve. Measures worst-case loss. The denominator of the Calmar ratio." },
  { term: "Calmar Ratio", category: "risk", definition: "CAGR / Max Drawdown. Measures return per unit of worst-case risk. >3 is considered excellent." },
  { term: "Value at Risk (VaR)", category: "risk", definition: "The maximum expected loss over a given time horizon at a given confidence level (e.g. 95% 1-day VaR). A standard risk metric in banking." },
  { term: "Conditional VaR (CVaR / Expected Shortfall)", category: "risk", definition: "The expected loss given that the loss exceeds the VaR threshold. Measures the tail beyond VaR." },
  { term: "Volatility Targeting", category: "risk", definition: "Scaling position size inversely to realized volatility to maintain a constant portfolio volatility target. Reduces drawdowns.", relatedStrategy: "index-vol-targeting" },
  { term: "Kelly Criterion", category: "risk", definition: "The optimal bet size for maximizing long-term growth: f* = edge / odds. Scales positions to the 'edge' of a strategy." },

  // ---------- MACRO & FX ----------
  { term: "Carry Trade", category: "macro", definition: "Borrow in a low-yield currency, invest in a high-yield currency, capturing the interest differential. Profitable persistently but subject to crash risk.", relatedStrategy: "carry-trade" },
  { term: "Uncovered Interest Parity (UIP)", category: "macro", definition: "The theory that the interest differential between two currencies should equal the expected change in the exchange rate. Empirically violated — the basis of the carry trade." },
  { term: "Triangular Arbitrage", category: "macro", definition: "Exploiting inconsistencies across three currencies (e.g. USD→EUR→GBP→USD). If the round-trip yields ≠1, an arbitrage exists.", relatedStrategy: "fx-triangular-arb" },
  { term: "Purchasing Power Parity (PPP)", category: "macro", definition: "The theory that exchange rates should adjust to equalize the price of identical goods across countries. Long-run anchor for FX." },
  { term: "Breakeven Inflation", category: "macro", definition: "The difference between nominal Treasury yields and TIPS yields. The market's expectation of future inflation." },
  { term: "Term Premium", category: "macro", definition: "The extra yield investors demand for holding long-duration bonds vs rolling short-term bonds. Can be negative." },

  // ---------- TRADING & EXECUTION ----------
  { term: "Backwardation", category: "trading", definition: "A futures curve where the front (near) contract trades at a higher price than the back (far) contract. Long positions earn a positive roll yield.", relatedStrategy: "roll-yields" },
  { term: "Contango", category: "trading", definition: "A futures curve where the front contract trades lower than the back. Long positions suffer negative roll yield (the 'cost of carry').", relatedStrategy: "roll-yields" },
  { term: "Roll Yield", category: "trading", definition: "The P&L from rolling a long futures position: as the front contract converges to spot, backwardation yields a gain, contango a loss.", relatedStrategy: "roll-yields" },
  { term: "Basis", category: "trading", definition: "The difference between the spot price and the futures price (or between two related instruments). Basis risk = the risk that this spread moves adversely." },
  { term: "Cash-and-Carry Arbitrage", category: "trading", definition: "Buy the underlying spot, short the futures, and carry to delivery. Locks in the mispricing when futures trade rich.", relatedStrategy: "cash-and-carry-index" },
  { term: "Market Making", category: "trading", definition: "The practice of quoting both bids and offers to capture the spread, while managing inventory risk. Profits from flow, not direction.", relatedStrategy: "market-making" },
  { term: "Slippage", category: "trading", definition: "The difference between the expected execution price and the actual fill price. A key cost in backtesting that is often underestimated." },
  { term: "Implied Correlation", category: "trading", definition: "The correlation level implied by index option vs single-stock option prices. Dispersion trading is a bet on this correlation.", relatedStrategy: "dispersion-trading" },
  { term: "Leveraged ETF (LETF)", category: "trading", definition: "An ETF that aims to deliver a multiple (e.g. 3×) of the daily return of an index. Daily rebalancing creates volatility drag in choppy markets.", relatedStrategy: "leveraged-etf" },

  // ---------- BLACK-SCHOLES ----------
  { term: "Black-Scholes Model", category: "options", definition: "The landmark option pricing model (1973). Assumes lognormal stock prices, constant vol, and no arbitrage. Gives the theoretical European option price via a closed-form formula." },
  { term: "Geometric Brownian Motion (GBM)", category: "options", definition: "The stochastic process underlying Black-Scholes: dS = μS·dt + σS·dW. Models asset prices with constant drift and volatility. Used in this terminal's price generation." },
  { term: "Risk-Neutral Valuation", category: "options", definition: "The principle that option prices can be computed by discounting expected payoffs under a risk-neutral measure (where the drift = risk-free rate)." },
  { term: "No-Arbitrage", category: "options", definition: "The foundational assumption that two portfolios with identical payoffs must have the same price. The basis for all derivative pricing." },
  { term: "Put-Call Parity", category: "options", definition: "The identity: C − P = S − K·e^(-rT). Relates call, put, stock, and bond prices. Violations create arbitrage (box spread)." },

  // ---------- ADDITIONAL TERMS ----------
  { term: "American Option", category: "options", definition: "An option that can be exercised at any time up to and including the expiration date. More valuable than the European equivalent due to early-exercise flexibility." },
  { term: "European Option", category: "options", definition: "An option that can only be exercised at expiration. Simpler to price (closed-form Black-Scholes); less flexible than American." },
  { term: "Assignment", category: "options", definition: "The process by which a short option holder is notified that the buyer has exercised. A short call assignee must deliver the underlying; a short put assignee must buy it." },
  { term: "Exercise", category: "options", definition: "The act of the option buyer invoking their right to buy (call) or sell (put) the underlying at the strike price. Most equity options auto-exercise if ITM at expiration." },
  { term: "Open Interest", category: "options", definition: "The total number of outstanding option contracts that have not been closed or exercised. A measure of liquidity and positioning." },
  { term: "Volatility of Volatility (VVIX)", category: "volatility", definition: "The volatility of the VIX index itself — a 'vol of vol' measure. High VVIX = the market's expectation of vol itself is unstable." },
  { term: "VIX Term Structure", category: "volatility", definition: "The curve of VIX futures prices across expirations. Typically in contango (later > earlier); flips to backwardation in stress. Traded via VIX futures calendar spreads.", relatedStrategy: "vix-futures-basis" },
  { term: "Volatility Carry", category: "volatility", definition: "The return from being short volatility when implied exceeds realized. Harvested via short options or short variance swaps; subject to crash risk.", relatedStrategy: "volatility-carry-etn" },
  { term: "Convexity", category: "fixed-income", definition: "The curvature in the price-yield relationship. Bonds with positive convexity gain more when yields fall than they lose when yields rise — an asymmetric, favorable property." },
  { term: "Key Rate Duration", category: "fixed-income", definition: "Sensitivity of a bond's price to a 1bp change at a specific point on the yield curve (holding other points constant). A more granular measure than effective duration." },
  { term: "Roll-Down", category: "fixed-income", definition: "The price appreciation as a bond 'rolls down' an upward-sloping yield curve toward its maturity. A component of fixed-income carry.", relatedStrategy: "roll-down-yield-curve" },
  { term: "Repo Rate", category: "fixed-income", definition: "The interest rate on a repurchase agreement — the implied cost of borrowing cash against collateral. A key short-term funding rate." },
  { term: "Factor Model", category: "stocks", definition: "A model that decomposes asset returns into exposures to common factors (market, size, value, momentum) plus idiosyncratic noise. The basis of factor investing." },
  { term: "Information Ratio", category: "risk", definition: "Active return divided by tracking error. Measures the consistency of outperformance vs a benchmark. The 'skill' ratio for active managers." },
  { term: "Tracking Error", category: "risk", definition: "The standard deviation of the difference between a portfolio's return and its benchmark's return. Measures how closely the portfolio follows the benchmark." },
  { term: "Beta-Adjusted Return", category: "risk", definition: "Return adjusted for the portfolio's beta exposure. Isolates alpha from market-directional P&L." },
  { term: "Purchasing Power Parity (PPP)", category: "macro", definition: "The theory that exchange rates should adjust to equalize the price of identical goods across countries. Long-run anchor for FX; violated in the short run." },
  { term: "Covered Interest Parity (CIP)", category: "macro", definition: "The no-arbitrage condition linking spot FX, forward FX, and interest rates: the forward premium equals the interest differential. Deviations (the 'cross-currency basis') signal funding stress." },
  { term: "Risk Reversal (FX)", category: "macro", definition: "In FX markets, the difference between the implied vol of an OTM call and an OTM put of the same delta. A standard market quote reflecting skew." },
  { term: "Open Interest", category: "trading", definition: "The total number of outstanding futures or options contracts not yet closed or delivered. A measure of market commitment and liquidity." },
  { term: "Contango / Backwardation", category: "trading", definition: "Contango: futures curve where later contracts are pricier (cost of carry). Backwardation: later contracts are cheaper (scarcity). Drives roll yield for long/short futures.", relatedStrategy: "roll-yields" },
  { term: "Convenience Yield", category: "trading", definition: "The non-monetary benefit of holding a physical commodity (e.g. ability to use in production). Explains backwardation in commodity curves." },
  { term: "Hedging Pressure", category: "trading", definition: "The net positioning of commercial hedgers in commodity futures (from CFTC COT data). Used as a contrarian signal — commercials tend to be informed." },
  { term: "Basis Risk", category: "trading", definition: "The risk that the price of a hedge does not move in lockstep with the underlying exposure. The residual risk after an imperfect hedge." },

  // ---------- ADDITIONAL TERMS (round 5) ----------
  { term: "American-style Exercise", category: "options", definition: "An option that can be exercised any time before expiry. American options are worth at least as much as European (early-exercise premium)." },
  { term: "At-the-Money (ATM)", category: "options", definition: "An option whose strike equals the current spot price. ATM options have the highest gamma and the most time value." },
  { term: "Bear Spread", category: "options", definition: "An option spread that profits from a decline in the underlying. Constructed with calls (bear call) or puts (bear put)." },
  { term: "Bull Spread", category: "options", definition: "An option spread that profits from a rise in the underlying. Constructed with calls (bull call) or puts (bull put)." },
  { term: "Calendar Spread", category: "options", definition: "A spread between two options of the same strike but different expirations. Profits from time decay and term-structure moves." },
  { term: "Condor", category: "options", definition: "A 4-strike structure (two inner shorts + two outer longs) that profits when the underlying stays within a range. Wider profit zone than a butterfly." },
  { term: "Credit Spread", category: "options", definition: "A spread that collects a net premium up front (e.g. short put spread). Maximum profit is the credit; risk is defined by the spread width." },
  { term: "Debit Spread", category: "options", definition: "A spread that costs a net premium up front (e.g. long call spread). Maximum profit is the spread width minus the debit; risk is the debit paid." },
  { term: "Delta Hedging", category: "options", definition: "Trading the underlying to offset the directional (delta) exposure of an option position, leaving mostly vega/gamma/theta exposure." },
  { term: "Diagonal Spread", category: "options", definition: "A spread combining different strikes AND different expirations. A hybrid of vertical and calendar spreads." },
  { term: "European-style Exercise", category: "options", definition: "An option exercisable only at expiry. Simpler to price (closed-form Black-Scholes); less flexible than American." },
  { term: "In-the-Money (ITM)", category: "options", definition: "An option with positive intrinsic value: a call when spot > strike, a put when spot < strike." },
  { term: "Iron Butterfly", category: "options", definition: "A defined-risk structure: short ATM straddle + long OTM wings. Profits if pinned at the strike; defined-risk version of a short straddle." },
  { term: "Leg", category: "options", definition: "A single component of a multi-leg option strategy. E.g. a long straddle has 2 legs; an iron condor has 4." },
  { term: "Naked Option", category: "options", definition: "A short option position without the underlying (for a call) or cash (for a put). Carries undefined risk." },
  { term: "Out-of-the-Money (OTM)", category: "options", definition: "An option with zero intrinsic value: a call when spot < strike, a put when spot > strike." },
  { term: "Ratio Spread", category: "options", definition: "A spread with an unequal number of long and short options (e.g. 1:2). One side has undefined risk if the wrong leg is short." },
  { term: "Risk Reversal", category: "options", definition: "Long OTM call + short OTM put (or vice versa). A low-cost directional trade; also a standard FX vol-skew quote." },
  { term: "Spread", category: "options", definition: "A combined option position of two or more legs. Spreads cap risk and reward vs naked options." },
  { term: "Strangle", category: "options", definition: "Long OTM call + long OTM put (same expiry). Cheaper than a straddle but needs a larger move to profit." },
  { term: "Synthetic", category: "options", definition: "A position constructed from options that replicates another instrument. E.g. long call + short put = synthetic long stock." },
  { term: "Vertical Spread", category: "options", definition: "A spread between two strikes of the same expiry. Bull/bear call/put spreads are all vertical spreads." },
  { term: "Wings", category: "options", definition: "The outer strikes in a butterfly or condor. The 'body' is the middle strike(s)." },

  { term: "CBOE", category: "volatility", definition: "Chicago Board Options Exchange — the largest US options exchange and home of the VIX index." },
  { term: "Contango (Vol)", category: "volatility", definition: "When VIX futures trade higher than the spot VIX (upward-sloping term structure). The norm in calm markets; bleeds long-VIX holders." },
  { term: "Backwardation (Vol)", category: "volatility", definition: "When VIX futures trade below the spot VIX (downward-sloping term structure). Signals stress; long VIX futures profit." },
  { term: "Vol-of-Vol", category: "volatility", definition: "The volatility of an asset's own volatility. High vol-of-vol = vol itself is unstable; relevant for VIX-option pricing (VVIX)." },
  { term: "Skewness", category: "volatility", definition: "The asymmetry of a return distribution. Negative skew (fat left tail) is typical of equities; positive skew of long options." },
  { term: "Kurtosis", category: "volatility", definition: "The 'fatness' of distribution tails. High kurtosis = more extreme outcomes than a normal distribution predicts." },

  { term: "Accrued Interest", category: "fixed-income", definition: "Interest earned on a bond since the last coupon date but not yet paid. Added to the clean price to get the dirty (full) price." },
  { term: "Barbell", category: "fixed-income", definition: "A bond portfolio split between short and long maturities, skipping the belly. Captures long yield + short liquidity." },
  { term: "Bullet", category: "fixed-income", definition: "A bond portfolio concentrated at a single target maturity. Maximizes exposure to one point on the yield curve." },
  { term: "Clean Price", category: "fixed-income", definition: "A bond's quoted price excluding accrued interest. The 'clean' price is what's typically quoted in markets." },
  { term: "Dirty Price", category: "fixed-income", definition: "A bond's full price including accrued interest. Clean price + accrued interest = dirty price." },
  { term: "Duration Matching", category: "fixed-income", definition: "Setting a portfolio's duration equal to the liability horizon to immunize against parallel yield shifts.", relatedStrategy: "bond-immunization" },
  { term: "Ladder", category: "fixed-income", definition: "A bond portfolio with evenly-spaced maturities. As rungs mature, reinvest at the long end — smooths reinvestment risk." },
  { term: "Maturity", category: "fixed-income", definition: "The date when a bond's principal is repaid. Longer maturity generally means higher duration and yield." },
  { term: "Par", category: "fixed-income", definition: "A bond trading at par = 100% of face value. Happens when coupon = yield." },
  { term: "Yield to Maturity (YTM)", category: "fixed-income", definition: "The IRR of a bond held to maturity — the annualized total return assuming coupons are reinvested at the YTM." },
  { term: "Zero-Coupon Bond", category: "fixed-income", definition: "A bond that pays no coupons, trading at a discount to face value. Return = face value − purchase price." },

  { term: "Cross-sectional", category: "stocks", definition: "Analysis comparing many assets at the same point in time (e.g. ranking stocks by momentum). Basis of stat-arb and factor investing." },
  { term: "Time-series", category: "stocks", definition: "Analysis of a single asset over time (e.g. trend-following). Contrasts with cross-sectional strategies." },
  { term: "Earnings Surprise (SUE)", category: "stocks", definition: "Standardized Unexpected Earnings = (actual EPS − forecast) / σ(forecast error). High SUE stocks drift (PEAD).", relatedStrategy: "earnings-momentum" },
  { term: "Fama-French Model", category: "stocks", definition: "A 3-factor asset-pricing model (market, size, value) extending CAPM. Later extended to 5 factors (adding profitability, investment)." },
  { term: "Idiosyncratic", category: "stocks", definition: "Asset-specific risk uncorrelated with common factors. Diversifiable in large portfolios." },
  { term: "Size Factor (SMB)", category: "stocks", definition: "Small Minus Big — the historical premium of small-cap stocks over large-caps. A Fama-French factor." },
  { term: "Value Factor (HML)", category: "stocks", definition: "High Minus Low — the premium of high book-to-market (value) stocks over low. A Fama-French factor." },
  { term: "Quality Factor", category: "stocks", definition: "The premium of high-quality (profitable, stable) stocks. A newer addition to the Fama-French 5-factor model." },
  { term: "Investment Factor", category: "stocks", definition: "The negative premium of high-investment firms (they underperform). A Fama-French 5-factor." },

  { term: "Correlation", category: "risk", definition: "A measure of how two assets move together, ∈ [-1, 1]. Low/negative correlation = diversification benefit." },
  { term: "Covariance", category: "risk", definition: "How two assets co-move (un-normalized). Correlation = covariance / (σ₁·σ₂)." },
  { term: "Drawdown Duration", category: "risk", definition: "How long an equity curve stays below its peak before recovering. A complement to max drawdown depth." },
  { term: "Efficient Frontier", category: "risk", definition: "The set of portfolios with the highest expected return for each risk level. Modern Portfolio Theory's optimal set." },
  { term: "Leverage", category: "risk", definition: "Using borrowed capital to amplify exposure. Increases both gains and losses; a key risk multiplier." },
  { term: "Liquidity Risk", category: "risk", definition: "The risk of being unable to exit a position without a large price concession. Often spikes in crises." },
  { term: "Modern Portfolio Theory (MPT)", category: "risk", definition: "Markowitz's framework for constructing portfolios that maximize return for a given variance. The foundation of mean-variance optimization." },
  { term: "Recovery Factor", category: "risk", definition: "Total return / max drawdown. Similar to Calmar; measures return per unit of worst-case loss." },
  { term: "Risk Parity", category: "risk", definition: "Allocating so each asset contributes equal risk to the portfolio (vs equal capital). Often leverages low-vol assets." },
  { term: "Tail Risk", category: "risk", definition: "The risk of extreme, low-probability losses. Hedged via OTM puts, tail-risk funds, or short variance." },

  { term: "Base Currency", category: "macro", definition: "The currency in which a portfolio's P&L is denominated. Often USD for global investors." },
  { term: "Cross Rate", category: "macro", definition: "An FX rate between two currencies, both quoted against a third (usually USD). E.g. EUR/GBP derived from EUR/USD and GBP/USD." },
  { term: "Currency Peg", category: "macro", definition: "A fixed exchange rate between a currency and a reference (usually USD or EUR). Maintained by central-bank intervention." },
  { term: "Forward Points", category: "macro", definition: "The interest-rate differential between two currencies, expressed as the forward-spot differential. Positive = the higher-yield currency trades at a forward discount." },
  { term: "Inflation Swap", category: "macro", definition: "A derivative exchanging a fixed rate for realized inflation. A direct, clean inflation hedge used by pension funds." },
  { term: "TIPS", category: "macro", definition: "Treasury Inflation-Protected Securities — US govt bonds whose principal adjusts with CPI. A liquid inflation hedge." },

  { term: "Ask (Offer)", category: "trading", definition: "The price at which a market-maker is willing to sell. The spread = ask − bid." },
  { term: "Bid", category: "trading", definition: "The price a market-maker is willing to pay. The spread = ask − bid; market-makers profit from the spread." },
  { term: "Dark Pool", category: "trading", definition: "A private trading venue that does not display orders publicly. Used to minimize market impact for large orders." },
  { term: "Fill", category: "trading", definition: "The execution of an order. A 'partial fill' means only part of the order was executed." },
  { term: "Front-running", category: "trading", definition: "Trading ahead of a known incoming order to profit from the price impact. Illegal for brokers; a form of toxic flow." },
  { term: "Market Impact", category: "trading", definition: "The adverse price move caused by one's own order. Larger orders in less liquid markets cause more impact." },
  { term: "Order Book", category: "trading", definition: "The list of outstanding bids and offers. The 'depth' of the book = how much size is available at each level." },
  { term: "Position Sizing", category: "trading", definition: "The art of determining how much capital to allocate to a trade. Kelly criterion and volatility targeting are common methods." },
  { term: "Rebalance", category: "trading", definition: "Adjusting a portfolio back to its target weights after drift. Frequency affects transaction costs and tax efficiency." },
  { term: "Toxic Flow", category: "trading", definition: "Order flow that systematically loses money for the market-maker (e.g. informed/latency-arb flow). The cost of providing liquidity." },
  { term: "VWAP", category: "trading", definition: "Volume-Weighted Average Price — a benchmark for execution quality. Algorithms aim to 'beat VWAP' over the day." },
  { term: "Whipsaw", category: "trading", definition: "A rapid reversal that triggers a trend-following signal then immediately stops it out. The main cost of trend-following in chop." },

  // ---------- ADDITIONAL TERMS (round 6) ----------
  { term: "Alpha-Neutral", category: "risk", definition: "A portfolio construction where idiosyncratic alpha offsets to zero, leaving only systematic (beta) exposure. A constraint in factor-tilt portfolios." },
  { term: "Beta-Neutral", category: "risk", definition: "A portfolio whose net beta is zero — long and short positions offset market exposure. Isolates alpha from market direction." },
  { term: "Co-skewness", category: "risk", definition: "The co-movement of an asset's returns with the market's squared returns. Measures contribution to portfolio skewness, beyond covariance." },
  { term: "Downside Deviation", category: "risk", definition: "The standard deviation of returns below the mean (or a threshold). The denominator of the Sortino ratio." },
  { term: "Information Coefficient (IC)", category: "risk", definition: "The correlation between predicted and realized returns. A measure of forecasting skill; IC > 0.05 is decent, > 0.1 strong." },
  { term: "Marginal VaR", category: "risk", definition: "The change in portfolio VaR from adding $1 of a specific asset. Used for risk-budgeting decisions." },
  { term: "Maximum Drawdown Duration", category: "risk", definition: "The longest time (in days/months) the equity curve stays below its prior peak. Measures recovery speed." },
  { term: "Omega Ratio", category: "risk", definition: "A risk-return ratio = (prob-weighted gains) / (prob-weighted losses) above a threshold. Captures the full distribution, not just mean/variance." },
  { term: "Sterling Ratio", category: "risk", definition: "Return / (max drawdown − 10% [arbitrary excess]). A Sharpe alternative penalizing drawdowns instead of volatility." },
  { term: "Treynor Ratio", category: "risk", definition: "Excess return / beta. Risk-adjusted return per unit of systematic (market) risk, vs Sharpe's total risk." },
  { term: "Upside Capture", category: "risk", definition: "The % of the benchmark's up-moves captured by a strategy. 100% = matches the benchmark's up-days; >100% outperforms." },
  { term: "Downside Capture", category: "risk", definition: "The % of the benchmark's down-moves captured. <100% = the strategy loses less than the benchmark in declines." },

  { term: "At-the-Money Forward (ATMF)", category: "options", definition: "An option whose strike equals the forward price. The standard reference for FX options (delta is quoted vs the forward)." },
  { term: "Black-76 Model", category: "options", definition: "A variant of Black-Scholes for pricing options on futures (where the underlying is the forward/futures price, not spot)." },
  { term: "Cash Settlement", category: "options", definition: "An option that settles in cash (the difference) rather than physical delivery. Standard for index options and VIX options." },
  { term: "Physical Settlement", category: "options", definition: "An option that settles by delivering (call) or receiving (put) the underlying. Standard for most single-stock equity options." },
  { term: "Exchange Option (Margrabe)", category: "options", definition: "An option to exchange one asset for another. Priced by the Margrabe formula — a Black-Scholes generalization." },
  { term: "Forward Start Option", category: "options", definition: "An option whose strike is set at a future date (typically as a % of then-spot). Used in executive compensation and cliquets." },
  { term: "Quanto Option", category: "options", definition: "An option whose payoff is in a different currency than the underlying, at a fixed FX rate. Removes FX risk from a foreign asset option." },
  { term: "Rainbow Option", category: "options", definition: "An option on the best (or worst, or average) of multiple underlyings. E.g. 'best-of' options on two indices." },
  { term: "Spread Option", category: "options", definition: "An option whose payoff depends on the spread between two underlyings (e.g. crack spread, spark spread)." },
  { term: "Volatility Swap (Vol Swap)", category: "options", definition: "A derivative paying the difference between realized vol and a strike. Linear in vol (vs variance swaps which are convex)." },

  { term: "Accrued Coupon", category: "fixed-income", definition: "The interest earned on a bond since its last coupon payment. The buyer pays the seller the accrued interest on top of the clean price." },
  { term: "Callable Bond", category: "fixed-income", definition: "A bond the issuer can redeem early at a set price. Gives the issuer negative convexity; trades at a higher yield vs non-callable." },
  { term: "Putable Bond", category: "fixed-income", definition: "A bond the holder can sell back to the issuer at a set price. Gives the holder positive convexity; trades at a lower yield." },
  { term: "Convertibility", category: "fixed-income", definition: "A bond feature allowing conversion into equity at a set ratio. The embedded call option makes convertibles part-bond, part-equity." },
  { term: "Covenant", category: "fixed-income", definition: "A contractual term in a bond indenture restricting issuer behavior (e.g. limits on leverage). Protects bondholders; weaker covenants = higher yield." },
  { term: "Default Recovery", category: "fixed-income", definition: "The % of face value recovered by bondholders if the issuer defaults. Senior secured ≈ 60-70%; subordinated ≈ 20-30%." },
  { term: "High-Yield (Junk) Bond", category: "fixed-income", definition: "A bond rated below investment grade (BB/Ba or lower). Higher yield to compensate for higher default risk." },
  { term: "Investment-Grade Bond", category: "fixed-income", definition: "A bond rated BBB-/Baa3 or higher. Lower default risk, lower yield than high-yield." },
  { term: "Make-Whole Call", category: "fixed-income", definition: "A callable bond provision requiring the issuer to pay the holder the NPV of remaining coupons + principal at a small spread. Effectively prevents early call except in distress." },
  { term: "Sinking Fund", category: "fixed-income", definition: "A bond provision requiring the issuer to retire a portion of the issue each year. Reduces default risk but adds reinvestment risk." },
  { term: "Subordination", category: "fixed-income", definition: "The priority order of claims in default: senior > mezzanine > subordinated. Lower priority = higher recovery risk = higher yield." },

  { term: "Active Share", category: "stocks", definition: "The % of a portfolio's holdings that differ from its benchmark. >100% = fully active; 0% = a closet index fund." },
  { term: "Earnings Yield", category: "stocks", definition: "Earnings per share / share price. The inverse of the P/E ratio; can be compared to bond yields (the 'Fed Model')." },
  { term: "Free Cash Flow Yield", category: "stocks", definition: "Free cash flow / market cap. A cash-based valuation metric less prone to accounting manipulation than earnings yield." },
  { term: "Growth Factor", category: "stocks", definition: "The premium of high-growth stocks. Rallied hard in the 2010s; negatively correlated with the value factor over that period." },
  { term: "Low-Volatility Factor", category: "stocks", definition: "The anomaly that low-vol/low-beta stocks deliver higher risk-adjusted returns. Traded via inverse-variance weighting.", relatedStrategy: "low-volatility-anomaly" },
  { term: "P/B (Price-to-Book)", category: "stocks", definition: "Market cap / book value. A core value metric — low P/B = cheap relative to accounting net worth." },
  { term: "P/E (Price-to-Earnings)", category: "stocks", definition: "Price / earnings per share. The most common valuation ratio; high P/E = expensive or high-growth expectations." },
  { term: "Residual Return", category: "stocks", definition: "Return after subtracting the factor-attributable portion. The 'pure alpha' unexplained by the factor model." },
  { term: "Sector Rotation", category: "stocks", definition: "Tactical shifting across sectors based on the business cycle. E.g. overweight tech in expansion, staples in contraction.", relatedStrategy: "sector-momentum-rotation" },
  { term: "Style Drift", category: "stocks", definition: "When an active manager's portfolio characteristics change over time (e.g. a value fund buying growth stocks). A monitoring concern." },

  { term: "COT Report", category: "macro", definition: "Commitments of Traders — a weekly CFTC report showing net positioning of commercial hedgers, large speculators, and small traders. Used as a positioning signal." },
  { term: "Current Account", category: "macro", definition: "A country's trade balance + net income from abroad. Persistent deficits can pressure the currency." },
  { term: "Hawkish / Dovish", category: "macro", definition: "Hawkish = central bank leaning toward tighter policy (fighting inflation). Dovish = leaning toward looser policy (supporting growth)." },
  { term: "Inverted Yield Curve", category: "macro", definition: "When short-term yields exceed long-term yields. A classic recession predictor; the 2s-10s inversion is most watched." },
  { term: "Purchasing Managers' Index (PMI)", category: "macro", definition: "A monthly survey of manufacturing/services activity. >50 = expansion; <50 = contraction. A key leading indicator." },
  { term: "Quantitative Easing (QE)", category: "macro", definition: "Central-bank purchases of long-dated bonds to lower long yields and stimulate the economy. Used when policy rates are already at zero." },
  { term: "Real Yield", category: "macro", definition: "Nominal yield − expected inflation. The real return a bondholder earns; negative real yields are a drag on real wealth." },
  { term: "Terms of Trade", category: "macro", definition: "A country's export prices / import prices. Improving terms of trade = currency tailwind." },
  { term: "Yield Curve Control (YCC)", category: "macro", definition: "A central-bank policy of pegging a specific yield (e.g. the BOJ's 10yr cap) via unlimited bond purchases." },

  // ---------- ADDITIONAL TERMS (round 7) ----------
  { term: "AR(1) Process", category: "risk", definition: "A first-order autoregressive process: x_t = φ·x_{t-1} + ε. The basis for modeling momentum (|φ|>0) vs mean-reversion (φ<0). pACF cuts off after lag 1." },
  { term: "Box-Jenkins Method", category: "risk", definition: "A systematic approach to ARIMA time-series modeling: identification, estimation, diagnostics. Uses ACF/pACF to identify model order." },
  { term: "Heteroskedasticity", category: "risk", definition: "Non-constant variance over time. Volatility clustering is a form of heteroskedasticity; modeled by ARCH/GARCH." },
  { term: "Ljung-Box Test", category: "risk", definition: "A statistical test for whether any of a group of autocorrelations of a time series are different from zero. Used to check if returns have predictable structure." },
  { term: "Stationarity", category: "risk", definition: "A time series with constant mean and variance over time. Returns are approximately stationary; prices are not (they have a unit root)." },
  { term: "Unit Root", category: "risk", definition: "A stochastic trend in a time series (e.g. a random walk). Price series typically have a unit root; returns are stationary." },
  { term: "White Noise", category: "risk", definition: "A time series of independent, identically distributed zero-mean random variables. Returns that are white noise cannot be predicted." },

  { term: "Asian Option", category: "options", definition: "An option whose payoff depends on the AVERAGE price over a period, not the spot at expiry. Lower vol than vanilla; cheaper. Used in commodities." },
  { term: "Barrier Option", category: "options", definition: "An option that activates (knock-in) or deactivates (knock-out) when the underlying crosses a barrier level. Cheaper than vanilla due to the barrier risk." },
  { term: "Binary (Digital) Option", category: "options", definition: "An option that pays a fixed amount if ITM at expiry, zero otherwise. Effectively a bet on a specific outcome; all-or-nothing payoff." },
  { term: "Cliquet Option", category: "options", definition: "A series of forward-start options that lock in gains periodically. Caps the period return; used in structured products to smooth payoffs." },
  { term: "Compound Option", category: "options", definition: "An option on an option. E.g. a call on a call — pays to exercise into the underlying option. Two exercise dates." },
  { term: "Lookback Option", category: "options", definition: "An option whose payoff depends on the max (call) or min (put) price over a period. Eliminates timing risk; expensive." },
  { term: "Power Option", category: "options", definition: "An option whose payoff is a power of the underlying. Amplifies convexity and leverage; exotic structure." },
  { term: "Shout Option", category: "options", definition: "An option where the holder can 'shout' once to lock in the intrinsic value at that point, retaining the right to a better payoff later." },

  { term: "Basis Point (bp)", category: "fixed-income", definition: "One-hundredth of a percent (0.01%). Bond yield changes are typically quoted in basis points; e.g. a 25bp move = 0.25%." },
  { term: "Convexity Bias", category: "fixed-income", definition: "The extra return (or cost) from holding positively-convex bonds due to the curvature of the price-yield relationship. Approx = ½ × convexity × Δy²." },
  { term: "Day Count Convention", category: "fixed-income", definition: "The rule for computing accrued interest (e.g. Actual/360, 30/360). Affects the dirty price and yield calculations." },
  { term: "Flat Yield Curve", category: "fixed-income", definition: "When yields are similar across maturities. Signals uncertainty about the growth/inflation outlook; less term premium." },
  { term: "Implied Vol (FI)", category: "fixed-income", definition: "The volatility implied by swaption prices. A measure of expected rate moves; traded via swaption straddles." },
  { term: "Roll-Down (FI)", category: "fixed-income", definition: "The price appreciation from a bond rolling toward maturity on an upward-sloping curve. A carry component for buy-and-hold investors." },
  { term: "Steepener Trade", category: "fixed-income", definition: "A DV01-neutral position betting that the yield-curve spread (e.g. 2s-10s) will widen. Profits when long yields rise faster than short.", relatedStrategy: "yield-curve-spread" },

  { term: "Beta Decomposition", category: "stocks", definition: "Splitting a portfolio's return into market (beta), factor, and idiosyncratic components. Reveals the sources of P&L." },
  { term: "Crowding", category: "stocks", definition: "When many investors hold similar positions in a factor/strategy. Increases crash risk when they unwind together; e.g. the quant crisis of 2007." },
  { term: "Factor Crowding", category: "stocks", definition: "Crowding specifically in a factor like value or momentum. Measured via aggregate positioning, valuations, and correlation among factor portfolios." },
  { term: "Market-Cap Weighting", category: "stocks", definition: "Weighting stocks by their market capitalization. The standard index methodology (S&P 500, MSCI). Pro: low turnover. Con: concentrated in biggest stocks." },
  { term: "Smart Beta", category: "stocks", definition: "Rule-based, factor-tilted indices (e.g. low-vol, momentum, value) that sit between passive market-cap and active. Cheaper than active." },
  { term: "Stock-Specific Risk", category: "stocks", definition: "Idiosyncratic risk from a single stock (earnings miss, scandal). Diversifiable in large portfolios but material in concentrated ones." },

  { term: "Beta-Adjusted Futures Hedge", category: "macro", definition: "Scaling a futures hedge by the beta of the underlying to the futures contract. E.g. hedge a high-beta stock with more futures than 1:1." },
  { term: "Bond Convexity Hedging", category: "macro", definition: "Hedging the convexity exposure of a mortgage or callable-bond portfolio using Treasury futures or swaptions. Reduces P&L from curve shifts." },
  { term: "Convenience Yield (Commodity)", category: "macro", definition: "The benefit of holding the physical commodity (e.g. ability to satisfy a production shortfall). Higher convenience = more backwardation." },
  { term: "Cross-Currency Basis", category: "macro", definition: "The deviation from covered interest parity. Negative USD/JPY basis = USD funding scarcity; trades as a measure of bank funding stress." },
  { term: "Dollar Index (DXY)", category: "macro", definition: "A trade-weighted index of USD vs EUR, JPY, GBP, CAD, SEK, CHF. The standard measure of broad USD strength/weakness." },
  { term: "Oil Term Structure", category: "macro", definition: "The curve of oil futures prices. Backwardation (front > back) signals tight supply; contango signals oversupply. Drives roll yield." },

  { term: "Execution Algorithm", category: "trading", definition: "A trading algorithm that breaks a large order into smaller pieces to minimize market impact. Examples: VWAP, TWAP, POV, implementation shortfall." },
  { term: "Hot Hand Fallacy", category: "trading", definition: "The mistaken belief that past success predicts future success (in random processes). The basis for momentum may be partly behavioral." },
  { term: "Implementation Shortfall", category: "trading", definition: "The total cost of executing a trade = (decision price − execution price) + opportunity cost. A comprehensive execution-cost metric." },
  { term: "Latency Arbitrage", category: "trading", definition: "Exploiting tiny price discrepancies across venues faster than others can react. A form of toxic flow; requires low-latency infrastructure." },
  { term: "POV (Percentage of Volume)", category: "trading", definition: "An execution algorithm that maintains a target % of market volume. Scales up in liquid markets, down in thin ones." },
  { term: "Slippage Model", category: "trading", definition: "A model estimating the price impact of a trade as a function of order size, ADV, and volatility. Critical for realistic backtests." },
  { term: "TWAP", category: "trading", definition: "Time-Weighted Average Price — an execution algorithm that slices an order evenly over a time window. Simpler than VWAP; doesn't need volume data." },

  // ---------- ADDITIONAL TERMS (round 8) ----------
  { term: "ARCH Model", category: "risk", definition: "Autoregressive Conditional Heteroskedasticity — an early model for volatility clustering. Today generalized by GARCH; the basis of vol forecasting." },
  { term: "GARCH Model", category: "risk", definition: "Generalized ARCH — extends ARCH by adding lagged conditional variance. The workhorse model for forecasting volatility in finance." },
  { term: "Brownian Motion", category: "risk", definition: "The continuous-time limit of a random walk — the basis of the Black-Scholes GBM assumption. dW is the 'shock' term." },
  { term: "Itô's Lemma", category: "risk", definition: "The stochastic-calculus chain rule. Allows computing the differential of a function of a stochastic process — key to deriving Black-Scholes." },
  { term: "Monte Carlo Simulation", category: "risk", definition: "Estimating quantities by generating many random paths and averaging. Used for path-dependent options and VaR where no closed-form exists." },
  { term: "Martingale", category: "risk", definition: "A stochastic process whose expected future value equals its current value. The mathematical basis of risk-neutral pricing and 'fair games'." },
  { term: "Markov Property", category: "risk", definition: "The future depends only on the present, not the past. GBM is Markov; the basis of efficient-market (random-walk) models." },
  { term: "Law of Large Numbers", category: "risk", definition: "The average of many iid samples converges to the expected value. The basis of Monte Carlo and diversification." },
  { term: "Central Limit Theorem", category: "risk", definition: "Sums of iid variables tend toward a normal distribution. Justifies the normality assumption for short-horizon returns." },
  { term: "Fat Tails", category: "risk", definition: "Return distributions with heavier tails than normal (high kurtosis). Empirically common; normal distributions underestimate tail risk." },

  { term: "Chooser Option", category: "options", definition: "An option that lets the holder decide (at a set date) whether it becomes a call or put. A 'complexity option' paying for flexibility." },
  { term: "Compound Interest", category: "options", definition: "Interest earned on prior interest. The mathematical driver of long-term compounding; Einstein's 'eighth wonder of the world'." },
  { term: "Delta-One", category: "options", definition: "A product/strategy with delta ≈ 1 — moves 1-for-1 with the underlying. E.g. swaps, futures, synthetic long stock." },
  { term: "Digital Spread", category: "options", definition: "A structure of two binary options at different strikes — pays a fixed amount within a range, zero outside." },
  { term: "Exotic Option", category: "options", definition: "Any option with non-standard payoff features (barrier, Asian, lookback, cliquet, etc.). OTC-traded; priced via models, not closed-form." },
  { term: "Knock-In / Knock-Out", category: "options", definition: "Barrier option triggers: knock-in activates when the barrier is crossed; knock-out deactivates. Both are cheaper than vanilla due to the barrier risk." },
  { term: "Lock-Out Period", category: "options", definition: "A period during which an option cannot be exercised or a barrier cannot trigger. Common in structured products." },
  { term: "Parisian Option", category: "options", definition: "A barrier option that triggers only after the underlying stays beyond the barrier for a continuous period. Harder to manipulate." },
  { term: "Volatility Surface", category: "options", definition: "The 3D plot of implied vol across strike AND expiry. The full input to options pricing models; arbitrage-free interpolation is non-trivial." },

  { term: "Asset Swap", category: "fixed-income", definition: "A swap converting a bond's fixed coupons to floating (or vice versa). Isolates credit risk from rate risk." },
  { term: "Bund", category: "fixed-income", definition: "German government bonds — the European benchmark for 10yr yields. Highly liquid; a eurozone safe-haven asset." },
  { term: "Gilts", category: "fixed-income", definition: "UK government bonds. The benchmark for sterling yields; similar role to Treasuries in USD." },
  { term: "JGB", category: "fixed-income", definition: "Japanese Government Bonds. The benchmark for yen yields; a key asset in the global carry trade as a low-yield funding currency." },
  { term: "OAT", category: "fixed-income", definition: "Obligations Assimilables du Trésor — French government bonds. Another European benchmark alongside Bunds." },
  { term: "Stripped Bond", category: "fixed-income", definition: "A bond whose coupons and principal are separated into zero-coupon instruments (e.g. STRIPS). Each cash flow trades on its own yield." },
  { term: "Total Return Swap (TRS)", category: "fixed-income", definition: "A swap where one party pays financing and receives the asset's total return (coupon + price change). Synthetic exposure without ownership." },
  { term: "Yield Beta", category: "fixed-income", definition: "The sensitivity of one bond's yield to another's. Used for cross-hedging when no perfect hedge instrument exists." },

  { term: "Anomaly", category: "stocks", definition: "An empirical regularity that contradicts the efficient-market hypothesis. E.g. momentum, value, low-vol — profitable and persistent, yet unexplained." },
  { term: "Behavioral Finance", category: "stocks", definition: "The study of how cognitive biases affect investment decisions. Explains anomalies like momentum via over/under-reaction." },
  { term: "Disposition Effect", category: "stocks", definition: "The tendency to sell winners too early and hold losers too long. A behavioral bias that contributes to momentum." },
  { term: "Earnings Quality", category: "stocks", definition: "The degree to which reported earnings reflect economic reality. Low quality (aggressive accounting) is a red flag for value traps." },
  { term: "Factor Mimicking Portfolio", category: "stocks", definition: "A long-short portfolio that captures a factor's return (e.g. HML for value). Used to measure factor premia and as a tradable factor exposure." },
  { term: "Limit Order", category: "stocks", definition: "An order to buy/sell at a specified price or better. Provides liquidity; risks non-execution if the price never reaches the limit." },
  { term: "Market Order", category: "stocks", definition: "An order to buy/sell immediately at the best available price. Takes liquidity; risks adverse fills in thin markets." },
  { term: "Smart Money", category: "stocks", definition: "Capital controlled by sophisticated investors (institutions, hedge funds). Their flow is often informative; retail flow is the counterparty." },
  { term: "Short Interest", category: "stocks", definition: "The total shares sold short as a % of float. High short interest signals bearish positioning and short-squeeze risk." },
  { term: "Short Squeeze", category: "stocks", definition: "A rapid price rise that forces short sellers to cover, pushing the price higher still. E.g. GameStop 2021." },

  { term: "Bretton Woods", category: "macro", definition: "The 1944 system of fixed exchange rates to the USD (and gold). Collapsed in 1971; the modern floating-rate FX regime began." },
  { term: "Capital Controls", category: "macro", definition: "Government restrictions on cross-border capital flows. Used to defend pegs or manage crises; distort the carry trade." },
  { term: "Deflation", category: "macro", definition: "A sustained decline in the general price level. Increases the real value of debt; a central-bank nightmare (Japan)." },
  { term: "Disinflation", category: "macro", definition: "A slowing of inflation (still positive, just lower). Often bullish for bonds and equities; distinct from deflation." },
  { term: "Stagflation", category: "macro", definition: "Stagnant growth + high inflation. The worst combination for both stocks and bonds; 1970s US is the classic example." },
  { term: "Safe Haven", category: "macro", definition: "An asset that rises (or holds value) in crises — e.g. USD, JPY, gold, Treasuries. Negative correlation with risk assets." },
  { term: "Risk-On / Risk-Off", category: "macro", definition: "A regime where markets move together based on risk appetite: 'risk-on' = equities rally, USD falls; 'risk-off' = the reverse." },
  { term: "Output Gap", category: "macro", definition: "The difference between actual and potential GDP. A positive gap = overheating (inflation risk); negative = slack (recession risk)." },

  { term: "Alpha Decay", category: "trading", definition: "The tendency for a strategy's edge to diminish over time as it becomes known/crowded. Measured by declining alpha after deployment." },
  { term: "Capacity", category: "trading", definition: "The maximum AUM a strategy can manage before transaction costs erode its edge. A key constraint for scale; stat-arb has low capacity." },
  { term: "Drawdown Recovery", category: "trading", definition: "The time to recover from a drawdown to a new equity high. A psychological and operational metric alongside max drawdown." },
  { term: "Overfitting", category: "trading", definition: "Fitting a model too closely to historical noise, reducing future performance. The #1 risk in backtesting; mitigated by out-of-sample testing." },
  { term: "Regime Shift", category: "trading", definition: "A structural change in market behavior (e.g. vol spike, correlation breakdown). Breaks strategies calibrated to the prior regime." },
  { term: "Stress Test", category: "trading", definition: "Simulating a portfolio under extreme scenarios (2008, COVID, etc.) to estimate tail losses. Complements VaR." },
  { term: "Survivorship Bias", category: "trading", definition: "Backtesting only on assets that survived — inflates returns. Must include delisted/failed assets for honest backtests." },
  { term: "Transaction Costs", category: "trading", definition: "The total cost of trading: commissions + spread + market impact + slippage. Often underestimated; can erode alpha." },

  // ---------- ADDITIONAL TERMS (round 9) ----------
  { term: "Backwardation", category: "macro", definition: "A futures curve where front (near) contracts trade higher than back (far) contracts. Indicates scarcity; provides positive roll yield to longs.", relatedStrategy: "roll-yields" },
  { term: "Contango", category: "macro", definition: "A futures curve where front contracts trade lower than back contracts. Indicates oversupply; creates negative roll yield (cost of carry) for longs.", relatedStrategy: "roll-yields" },
  { term: "Cost of Carry", category: "macro", definition: "The cost of holding a position: financing + storage − income (dividends/coupons). The basis between spot and futures prices." },
  { term: "Forward Curve", category: "macro", definition: "The set of forward/futures prices across expirations. Shape (contango vs backwardation) carries information about supply/demand and the cost of carry." },
  { term: "Spot-Future Parity", category: "macro", definition: "F = S·e^((r−q)·T). The no-arbitrage relationship between spot, forward, financing (r), and yield (q). Basis deviations = arbitrage." },
  { term: "Term Structure", category: "macro", definition: "The relationship between yields/volatilities/prices across maturities. Traded via flatteners/steepeners (rates) or calendar spreads (futures)." },

  { term: "Black-Scholes-Merton (BSM)", category: "options", definition: "The full Black-Scholes model with continuous dividends (Merton's extension). Reduces to BS when dividend yield q=0." },
  { term: "Garman-Kohlhagen", category: "options", definition: "The Black-Scholes variant for FX options, with two interest rates (domestic and foreign). The standard for FX option pricing." },
  { term: "Heston Model", category: "options", definition: "A stochastic-volatility model where vol itself follows a mean-reverting square-root process. Produces realistic smile and skew." },
  { term: "Local Volatility Model", category: "options", definition: "A model where vol is a deterministic function of spot and time, calibrated to the full volatility surface. Used for exotic pricing." },
  { term: "Stochastic Volatility", category: "options", definition: "A model where volatility itself is random (e.g. Heston, SABR). Captures vol clustering and the smile/skew that constant-vol BS cannot." },
  { term: "SABR Model", category: "options", definition: "Stochastic Alpha-Beta-Rho — a popular stochastic-vol model for interest-rate options. Captures both smile and skew with few parameters." },
  { term: "Volatility Arbitrage", category: "options", definition: "Trading the difference between implied and realized volatility — e.g. shorting options when IV > expected RV, delta-hedging the residual." },
  { term: "Volatility Term Structure", category: "options", definition: "IV as a function of expiry. Upward-sloping in calm markets (longer = higher); inverts (downward) during stress." },

  { term: "Beta-Weighted", category: "risk", definition: "Scaling position sizes by their beta to a common benchmark. Allows risk-equivalent comparison across assets with different volatilities." },
  { term: "Factor Model (Statistical)", category: "risk", definition: "A factor model where factors are extracted via PCA rather than specified a priori. Captures the dominant co-movements without economic interpretation." },
  { term: "Greeks Aggregation", category: "risk", definition: "Summing option Greeks across a portfolio to get net exposures. Used to manage the book's directional, vol, and time risk." },
  { term: "Marginal Risk Contribution", category: "risk", definition: "The marginal change in portfolio risk from a small increase in one asset's weight. Sum × weight = total risk = the Euler decomposition." },
  { term: "Maximum Entropy", category: "risk", definition: "A distribution-fitting principle: choose the least-assuming distribution consistent with known constraints (mean, variance). Used in risk modeling." },
  { term: "Parametric VaR", category: "risk", definition: "VaR computed from the mean and standard deviation assuming a normal distribution. Fast but underestimates tail risk for non-normal returns." },
  { term: "Risk Budgeting", category: "risk", definition: "Allocating risk (not capital) across assets/factors based on a target risk budget. A generalization of risk parity." },
  { term: "Semi-Deviation", category: "risk", definition: "Standard deviation of returns below the mean. The denominator of the Sortino ratio; a downside-only volatility measure." },
  { term: "Spectral Risk Measure", category: "risk", definition: "A risk measure weighting losses by a risk-aversion spectrum. Coherent and tail-aware; generalizes CVaR." },

  { term: "Basis (Commodity)", category: "fixed-income", definition: "The difference between a commodity's spot price and its futures price. Basis risk = the risk this spread moves unexpectedly." },
  { term: "Cheapest-to-Deliver (CTD)", category: "fixed-income", definition: "The bond cheapest to deliver into a futures contract. Drives the futures' DV01 and the basis; changes as yields move." },
  { term: "Convexity Adjustment (Futures)", category: "fixed-income", definition: "An adjustment to Eurodollar / SOFR futures rates to account for the convexity bias vs FRA/OIS rates. Significant for long-dated contracts." },
  { term: "DV01-Neutral", category: "fixed-income", definition: "A position sized so a 1bp parallel yield move has zero P&L. The standard for curve-relative-value trades.", relatedStrategy: "ddn-butterfly" },
  { term: "OIS Discounting", category: "fixed-income", definition: "Discounting swap cashflows at the OIS (overnight indexed swap) rate rather than LIBOR. Post-2008 standard for collateralized derivatives." },
  { term: "Roll-Down (Bonds)", category: "fixed-income", definition: "The price appreciation as a bond slides toward maturity on an upward-sloping curve. Captured by buy-and-hold investors.", relatedStrategy: "roll-down-yield-curve" },
  { term: "Swap Rate", category: "fixed-income", definition: "The fixed rate paid in a swap that makes the PV of fixed and floating legs equal. The benchmark for the interest-rate swap market." },
  { term: "TED Spread", category: "fixed-income", definition: "3-month LIBOR − 3-month T-bill. A classic measure of bank credit risk / funding stress; spiked in 2008." },

  { term: "Algorithmic Trading", category: "trading", definition: "Trading driven by computer algorithms — from simple VWAP/TWAP to complex statistical-arb and ML strategies. Encompasses most modern institutional volume." },
  { term: "Backtest Overfitting", category: "trading", definition: "Tuning strategy parameters to maximize historical performance, creating an illusion of edge. The most common backtesting trap; mitigated by out-of-sample testing." },
  { term: "Data Mining Bias", category: "trading", definition: "The bias from testing many strategies on the same data and selecting the best by historical performance. P-hacking in quant form." },
  { term: "Forward Testing", category: "trading", definition: "Running a strategy in live (paper) trading after backtesting. The bridge between backtest and live deployment." },
  { term: "Look-Ahead Bias", category: "trading", definition: "Using information in a backtest that wasn't actually available at the time. E.g. using revised economic data in the unrevised period. A silent backtest killer." },
  { term: "Out-of-Sample Test", category: "trading", definition: "Testing a strategy on data not used for calibration. The gold standard for validating that an edge is real, not overfit." },
  { term: "Parameter Stability", category: "trading", definition: "The robustness of a strategy's performance across parameter settings. Unstable = overfit; stable = real signal." },
  { term: "Signal-to-Noise Ratio", category: "trading", definition: "The ratio of predictable signal to random noise in returns. Low S/N is the norm; edge is small and requires careful extraction." },

  { term: "Book Value", category: "stocks", definition: "Net assets on the balance sheet = total assets − intangibles − liabilities. The denominator of the price-to-book ratio; a value-investing anchor." },
  { term: "Dividend Yield", category: "stocks", definition: "Annual dividends / share price. A value component and an income component; central to equity carry strategies." },
  { term: "Earnings Per Share (EPS)", category: "stocks", definition: "Net income / shares outstanding. The numerator of the P/E ratio; the bottom-line profitability per share." },
  { term: "Free Cash Flow (FCF)", category: "stocks", definition: "Operating cash flow − capex. The cash a business generates after maintaining its asset base; the basis of intrinsic valuation." },
  { term: "Net Margin", category: "stocks", definition: "Net income / revenue. A profitability measure; high-margin businesses (software) command premium multiples." },
  { term: "Return on Equity (ROE)", category: "stocks", definition: "Net income / shareholders' equity. A key profitability ratio; the 'return' in the DuPont decomposition of ROE = margin × turnover × leverage." },
  { term: "Sector ETF", category: "stocks", definition: "An ETF tracking a single sector (XLK tech, XLF financials, XLE energy). The building block of sector-rotation strategies.", relatedStrategy: "sector-momentum-rotation" },
  { term: "Stock Buyback", category: "stocks", definition: "A company repurchasing its own shares. Reduces share count, boosts EPS; a common use of corporate cash in lieu of dividends." },

  // ---------- ADDITIONAL TERMS (round 10) ----------
  { term: "Kernel Density Estimation (KDE)", category: "risk", definition: "A non-parametric way to estimate a return distribution's PDF. Smooths the histogram via Gaussian kernels; reveals fat tails and skew vs a normal." },
  { term: "Silverman's Rule", category: "risk", definition: "A heuristic for KDE bandwidth: h = 1.06·σ·n^(-1/5). Balances bias vs variance; the default in most KDE implementations." },
  { term: "Q-Q Plot", category: "risk", definition: "Quantile-quantile plot comparing sample quantiles to a theoretical (usually normal) distribution. Deviations from the line reveal fat tails / skew." },
  { term: "Jarque-Bera Test", category: "risk", definition: "A statistical test for normality based on skewness and kurtosis. Rejects normality for fat-tailed financial returns — almost always." },
  { term: "Anderson-Darling Test", category: "risk", definition: "A statistical test for whether a sample comes from a specified distribution. More sensitive to tails than Kolmogorov-Smirnov." },
  { term: "Hill Estimator", category: "risk", definition: "An estimator for the tail index of a heavy-tailed distribution. Used to quantify extreme-value risk beyond normal assumptions." },
  { term: "Copula", category: "risk", definition: "A function linking marginal distributions into a joint distribution. Captures dependence structure separately from marginals; key for tail-dependence modeling." },
  { term: "Tail Dependence", category: "risk", definition: "The probability that one asset crashes given another crashes. Upper/lower tail dependence; copulas model this. Critical for crisis diversification." },
  { term: "Extreme Value Theory (EVT)", category: "risk", definition: "A branch of statistics modeling the tails of distributions. Used for estimating very-low-probability events (100-year floods in finance)." },
  { term: "Expected Shortfall (ES)", category: "risk", definition: "Same as CVaR — the expected loss given the loss exceeds VaR. A coherent risk measure (unlike VaR); the Basel post-2008 standard." },

  { term: "Volga (Vomma)", category: "options", definition: "The second derivative of option price w.r.t. volatility — volga = ∂²V/∂σ². Measures how vega itself changes as vol moves; relevant for vol-of-vol trades." },
  { term: "Vanna", category: "options", definition: "The cross-derivative ∂²V/∂S∂σ — how delta changes as vol moves (or vega as spot moves). Relevant for skew-sensitive books." },
  { term: "Charm", category: "options", definition: "∂Δ/∂t — how delta changes as time passes. Important for delta-hedging frequency; causes drift in hedge ratios over weekends." },
  { term: "Color", category: "options", definition: "∂Γ/∂t — how gamma changes as time passes. Peaks ATM as expiry approaches; drives the 'pin risk' acceleration." },
  { term: "Speed", category: "options", definition: "∂Γ/∂S = ∂³V/∂S³ — the rate of change of gamma w.r.t. spot. A third-order Greek; relevant for large books with gamma convexity." },
  { term: "Ultima", category: "options", definition: "∂³V/∂σ³ — the third derivative w.r.t. vol. A higher-order Greek for vol-of-vol-of-vol; exotic but used in complex structures." },
  { term: "Zomma", category: "options", definition: "∂Γ/∂σ — how gamma changes as vol moves. Relevant for gamma-scalping strategies that depend on vol regime." },
  { term: "DvegaDtime", category: "options", definition: "∂ν/∂t — how vega decays as time passes. Long-dated options have stable vega; short-dated options lose vega fast." },

  { term: "Duration Times Spread (DTS)", category: "fixed-income", definition: "A credit-risk measure = duration × spread. Captures the price sensitivity to spread changes; used for corporate bond risk." },
  { term: "Spread Duration", category: "fixed-income", definition: "The sensitivity of a bond's price to a 1bp change in its spread over the risk-free curve. A key credit-risk metric." },
  { term: "Key Rate Duration (FI)", category: "fixed-income", definition: "Duration w.r.t. a single point on the yield curve, holding others constant. Reveals curve-shape risk vs parallel-shift risk." },
  { term: "Spread Convexity", category: "fixed-income", definition: "The curvature of price w.r.t. spread changes. High-spread-convexity bonds gain more when spreads tighten than they lose when spreads widen." },
  { term: "Loss Given Default (LGD)", category: "fixed-income", definition: "1 − recovery rate. The % of exposure lost if a default occurs. Combined with PD (probability of default) for expected loss." },
  { term: "Probability of Default (PD)", category: "fixed-income", definition: "The likelihood a borrower defaults within a horizon. Multiplied by LGD and exposure = expected loss; the core of credit-risk modeling." },
  { term: "Expected Loss", category: "fixed-income", definition: "PD × LGD × exposure. The average loss a lender expects; priced into the spread over risk-free." },
  { term: "Credit Migration", category: "fixed-income", definition: "A rating downgrade (or upgrade) of an issuer. Downgrades force some holders (rating-constrained) to sell, often at a loss." },

  { term: "Machine Learning (ML)", category: "stocks", definition: "Algorithms that learn patterns from data — regression, trees, neural nets. Applied to return prediction, factor selection, and signal combination." },
  { term: "Random Forest", category: "stocks", definition: "An ensemble of decision trees trained on bootstrapped samples. Robust to overfitting; used for feature importance and classification." },
  { term: "Gradient Boosting", category: "stocks", definition: "An ensemble method building trees sequentially, each correcting prior errors. XGBoost / LightGBM dominate tabular-data competitions." },
  { term: "Neural Network", category: "stocks", definition: "A model of interconnected layers learning non-linear features. Deep variants (LSTM, Transformer) excel at sequence prediction but overfit financial data easily.", relatedStrategy: "crypto-ann" },
  { term: "k-Nearest Neighbors (kNN)", category: "stocks", definition: "A simple ML method: predict based on the k most similar historical examples. Used in the paper for single-stock return prediction.", relatedStrategy: "knn-ml" },
  { term: "Naïve Bayes", category: "stocks", definition: "A probabilistic classifier assuming feature independence. The paper uses Bernoulli Naïve Bayes for crypto sentiment classification.", relatedStrategy: "sentiment-naive-bayes" },
  { term: "Cross-Validation", category: "stocks", definition: "Splitting data into train/test folds to assess model generalization. K-fold CV is standard; time-series CV respects temporal order." },
  { term: "Feature Engineering", category: "stocks", definition: "Constructing predictive features from raw data. Often more impactful than model choice; the art of ML in finance." },
  { term: "Hyperparameter Tuning", category: "stocks", definition: "Selecting model parameters (e.g. tree depth, learning rate) via search + CV. Critical for performance; risks overfitting if done on test data." },
  { term: "Ensemble Method", category: "stocks", definition: "Combining multiple models' predictions (bagging, boosting, stacking). Reduces variance and often beats any single model." },

  { term: "Crack Spread", category: "macro", definition: "The difference between refined product prices (gasoline + heating oil) and crude oil. Refinery margin; traded as a spread option." },
  { term: "Spark Spread", category: "macro", definition: "Electricity price − (heat rate × gas price). Power-plant margin; traded in energy markets. A measure of generation profitability.", relatedStrategy: "energy-spark-spread" },
  { term: "Crush Spread", category: "macro", definition: "Soybean meal + soybean oil − soybeans. The soybean-processor margin; traded on CBOT." },
  { term: "Calendar Spread (Commodity)", category: "macro", definition: "Long one expiry, short another of the same commodity. Captures term-structure moves with reduced directional exposure." },
  { term: "Inter-Commodity Spread", category: "macro", definition: "Long one commodity, short a related one (e.g. gold vs silver, WTI vs Brent). Trades the relative-value relationship." },
  { term: "Seasonality", category: "macro", definition: "Recurring patterns tied to the calendar (e.g. natural gas winter demand, agricultural harvest cycles). Traded via seasonal spread strategies." },
  { term: "Weather Derivative", category: "macro", definition: "A derivative paying based on temperature (HDD/CDD) or precipitation. Used by utilities, agriculture, and energy firms to hedge weather risk.", relatedStrategy: "weather-demand-hedging" },

  { term: "Order Flow", category: "trading", definition: "The stream of executed buy/sell orders. Imbalance predicts short-term price moves; the basis of microstructure and order-flow strategies." },
  { term: "Order Book Imbalance", category: "trading", definition: "The asymmetry between bid and ask sizes at the top of the book. A short-term predictor used by market-makers and HFT." },
  { term: "Inventory Risk", category: "trading", definition: "The risk a market-maker holds an unwanted position due to filling orders. Managed via spread width and inventory limits." },
  { term: "Adverse Selection", category: "trading", definition: "The tendency for filled orders to be on the wrong side — informed flow hits stale quotes. The cost of providing liquidity." },
  { term: "Co-location", category: "trading", definition: "Placing trading servers in the exchange's data center for minimum latency. Essential for HFT; a barrier to entry." },
  { term: "Smart Order Router", category: "trading", definition: "An algorithm splitting an order across multiple venues to achieve best execution. Critical in fragmented markets." },
  { term: "Best Execution", category: "trading", definition: "The regulatory obligation to seek the most favorable terms for client orders. Documented via execution-quality reports." },
  { term: "Marking-to-Market", category: "trading", definition: "Valuing positions at current market prices. Required for daily P&L and margin; the basis of fair-value accounting." },

  // ---------- ADDITIONAL TERMS (round 11) ----------
  { term: "Cointegration Test", category: "risk", definition: "A statistical test (e.g. Engle-Granger, Johansen) for whether two series are cointegrated — i.e. share a long-run equilibrium. The basis of pairs trading.", relatedStrategy: "pairs-trading" },
  { term: "Dickey-Fuller Test", category: "risk", definition: "A unit-root test for stationarity. Rejecting the null (unit root) implies the series is stationary; used to check mean-reversion." },
  { term: "Hurst Exponent", category: "risk", definition: "A measure of long-memory: H>0.5 = trending/persistent, H=0.5 = random walk, H<0.5 = mean-reverting. Used to classify return behavior." },
  { term: "Ornstein-Uhlenbeck", category: "risk", definition: "A mean-reverting stochastic process: dX = κ(θ−X)dt + σdW. The continuous-time model for pairs-trading spreads." },
  { term: "Half-Life", category: "risk", definition: "The time for a mean-reverting spread to halve its deviation from equilibrium: ln(2)/κ. Shorter = faster reversion; trades held longer are unprofitable." },
  { term: "Granger Causality", category: "risk", definition: "A statistical test for whether one time series predicts another (beyond its own lags). Used in lead-lag and macro nowcasting." },
  { term: "Information Coefficient (Rank IC)", category: "risk", definition: "Spearman-rank correlation between predicted and realized returns. Robust to outliers; the standard cross-sectional skill metric." },
  { term: "Hit Rate", category: "risk", definition: "The % of forecasts that got the direction right. A binary accuracy measure; complementary to the magnitude-aware Sharpe." },
  { term: "Kalman Filter", category: "risk", definition: "An optimal recursive estimator for linear-Gaussian state-space models. Used for dynamic hedge ratios, signal extraction, and tracking." },
  { term: "EWMA", category: "risk", definition: "Exponentially-Weighted Moving Average — weights recent observations more. RiskMetrics uses EWMA for volatility forecasting (λ≈0.94)." },

  { term: "Delta Hedging Frequency", category: "options", definition: "How often a delta-hedged book is re-hedged. Continuous = zero risk but infinite costs; discrete trades off risk vs transaction costs." },
  { term: "Gamma P&L", category: "options", definition: "P&L from the convexity of an option position when delta-hedged — ½Γ(ΔS)² per move. The source of 'gamma scalping' income for long-gamma books." },
  { term: "Theta P&L", category: "options", definition: "P&L from time decay — Θ per day. Positive for short options; the income that funds the gamma risk in a delta-hedged book." },
  { term: "Vega P&L", category: "options", definition: "P&L from a change in implied vol: ν × ΔIV. Long-vega books profit when vol rises; the basis of VRP harvesting." },
  { term: "Pinned-At-Strike", category: "options", definition: "When the underlying closes expiry exactly at a strike — maximum pin risk, uncertain assignment. A risk for short straddle/strangle writers." },
  { term: "Implied Volatility Crush", category: "options", definition: "The sharp drop in IV after an event (earnings, M&A) resolves. Long options lose both intrinsic and IV; short options profit." },
  { term: "Volatility Surface Arbitrage", category: "options", definition: "Exploiting inconsistencies across the implied-vol surface (calendar, vertical, or butterfly arbitrages). Ensures a no-arb surface." },
  { term: "Local Volatility Surface", category: "options", definition: "A deterministic vol function σ(S,t) calibrated to the full IV surface. Used to price path-dependent exotics consistently with vanillas." },

  { term: "Asset-Backed Security (ABS)", category: "fixed-income", definition: "A bond backed by a pool of generating assets (auto loans, credit cards, student loans). Cash flows come from the underlying assets." },
  { term: "Mortgage-Backed Security (MBS)", category: "fixed-income", definition: "An ABS backed by mortgage loans. Prepayment risk (homeowners refinancing) creates negative convexity.", relatedStrategy: "mbs-trading" },
  { term: "Collateralized Debt Obligation (CDO)", category: "fixed-income", definition: "A structured product slicing a debt pool into tranches by priority. Equity tranches absorb first losses; senior tranches are last.", relatedStrategy: "cdo-equity-carry" },
  { term: "Tranche", category: "fixed-income", definition: "A slice of a CDO/ABS by loss priority: senior, mezzanine, equity. Lower-priority tranches carry more default risk for higher yield." },
  { term: "Waterfall", category: "fixed-income", definition: "The rule for distributing cash flows and losses across CDO tranches. Senior gets paid first; equity absorbs losses first." },
  { term: "Default Correlation", category: "fixed-income", definition: "The tendency for issuers to default together. High correlation = senior tranches riskier; low correlation = equity tranches riskier. Traded via correlation." },
  { term: "Prepayment Risk", category: "fixed-income", definition: "The risk that borrowers prepay (refinance) early, shortening bond duration. Reduces MBS value when rates fall." },
  { term: "Extension Risk", category: "fixed-income", definition: "The opposite of prepayment risk — borrowers slow prepayments when rates rise, extending duration. A risk for MBS holders." },

  { term: "Earnings Whisper", category: "stocks", definition: "An unofficial earnings estimate aggregated from buy-side analysts. Often more accurate than the consensus; trades ahead of the print." },
  { term: "Guidance", category: "stocks", definition: "Management's forward-looking forecast for revenue/EPS. The guide matters more than the beat; 'lowered guidance' sells off hard." },
  { term: "Same-Store Sales", category: "stocks", definition: "Retail revenue from stores open >1yr — strips out new-store growth. The cleanest comparable-store growth metric." },
  { term: "Whisper Number", category: "stocks", definition: "An unofficial earnings estimate circulating among traders. Beating the whisper (not just consensus) drives post-earnings drift." },
  { term: "IPO Lockup", category: "stocks", definition: "A period (typically 180 days) after an IPO during which insiders can't sell. Expiry often brings selling pressure; traded as an event." },
  { term: "Short Interest Ratio (Days to Cover)", category: "stocks", definition: "Short interest / average daily volume. High = many days of buying needed to cover; a squeeze risk indicator." },
  { term: "Float", category: "stocks", definition: "Shares available for public trading (excludes insider/locked-up shares). Low float = more volatility; a factor in squeezes." },
  { term: "Market Capitalization", category: "stocks", definition: "Share price × shares outstanding. The size of a company; large-cap / mid-cap / small-cap thresholds are conventionally $10B / $2B." },

  { term: "Quantitative Tightening (QT)", category: "macro", definition: "The reverse of QE — central bank selling (or not reinvesting) bonds to shrink its balance sheet. Tightens financial conditions; raises long yields." },
  { term: "Forward Guidance", category: "macro", definition: "Central-bank communication about the future path of rates. Shapes market expectations; a tool in itself, separate from actual rate moves." },
  { term: "Dot Plot", category: "macro", definition: "The Fed's quarterly summary of FOMC members' rate-path expectations. Each dot = one member's projection; the median dot moves markets." },
  { term: "Beige Book", category: "macro", definition: "The Fed's qualitative summary of regional economic conditions, published 8x/yr. Reads for soft signals not in the hard data." },
  { term: "Non-Farm Payrolls (NFP)", category: "macro", definition: "The monthly US jobs report — the most market-moving macro release. Big surprises move equities, bonds, and the USD sharply." },
  { term: "CPI", category: "macro", definition: "Consumer Price Index — the headline inflation measure. CPI surprises move real yields, breakevens, and rate expectations." },
  { term: "PCE", category: "macro", definition: "Personal Consumption Expenditures — the Fed's preferred inflation gauge (vs CPI). Core PCE is the target metric for the 2% mandate." },
  { term: "FOMC", category: "macro", definition: "Federal Open Market Committee — the Fed's rate-setting body, meeting 8x/yr. The statement, dot plot, and press conference all move markets." },

  { term: "Rebate", category: "trading", definition: "A payment from an exchange to liquidity providers (market makers) for posting quotes. Reduces the effective cost of providing liquidity." },
  { term: "Access Fee", category: "trading", definition: "A charge (to liquidity takers) on exchanges that offer rebates. The other side of the maker-taker model; controversial for distorting order routing." },
  { term: "Maker-Taker", category: "trading", definition: "An exchange fee model: makers get rebates, takers pay fees. incentivizes liquidity provision; criticized for routing distortions." },
  { term: "Tick Size", category: "trading", definition: "The minimum price increment (e.g. $0.01 for US equities, $0.25 for some futures). Smaller ticks = tighter spreads; larger = more maker profits." },
  { term: "Block Trade", category: "trading", definition: "A large privately-negotiated trade reported to the exchange after execution. Minimizes market impact; common for institutional size." },
  { term: "Dark Pool (ATS)", category: "trading", definition: "An Alternative Trading System that doesn't display orders. Reduces information leakage for large orders; ~40% of US equity volume." },
  { term: "RFQ (Request for Quote)", category: "trading", definition: "Asking dealers for quotes on a specific size/instrument. Standard for less-liquid fixed income and OTC derivatives." },
  { term: "Cross", category: "trading", definition: "An internal match of a buy and sell order within the same broker, reported to the exchange. Minimizes market impact for matching client flow." },
];

export function searchGlossary(query: string): GlossaryTerm[] {
  if (!query.trim()) return GLOSSARY;
  const q = query.toLowerCase();
  return GLOSSARY.filter(
    (t) =>
      t.term.toLowerCase().includes(q) ||
      t.definition.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  );
}

export function getGlossaryByCategory(cat: GlossaryCategory): GlossaryTerm[] {
  return GLOSSARY.filter((t) => t.category === cat);
}

// Wrapper exports for test compatibility
export const GLOSSARY_TERMS = GLOSSARY;

export function getTermsByCategory(cat: string): GlossaryTerm[] {
  return getGlossaryByCategory(cat as GlossaryCategory);
}
